import Head from 'next/head';
import { useEffect } from 'react';
import styles from '~/styles/pages/PageIndex.module.scss';
import { CustomScroll } from '~/lib/scroll';

export default function Index() {
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const scroll = new CustomScroll();
    scroll.initElements();
    scroll.addEvents();

    return () => {
      scroll.removeEvents();
    };
  }, []);

  return (
    <div data-scroll-container="true">
      <div className={styles.root}>
        <Head>
          <title>Next.js Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className={styles.title}>Custom Scroll</h1>
        <ul className={styles.list}>
          {[...Array(10)].map((_, i) => (
            <li className={styles.item} key={i}>
              <h2 className={styles.heading}>{`Section${i + 1}`}</h2>
              <p className={styles.desc}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
